version: '3'
# Like containers
services:
  # First one is redis server
  redis-server:
    image: 'redis'
  # Second one is my node.js server
  node-app:
    restart: always
    build: .
    ports:
      - "4001:8081"

