
name: unittests
on: push

jobs:

  Everything:
    runs-on: ubuntu-22.04
    container: python:3.11.1
    steps:
      - uses: actions/checkout@v3
      - run: python run.py --install
      - run: python run.py --unittest rock_paper_scissors_game/test_rps_game.py tic_tac_toe_game/test_ttt_game.py
      - run: python run.py --pytest tic_tac_toe_game/test_pytest_ttt_game.py tests_iot_api/test_iot_api.py
        with:
          API_KEY: ${{ secrets.API_KEY }}
        env:
          API_KEY: ${{ secrets.API_KEY }}